name: in_app_reminder
description: A Flutter plugin for creating native reminders with support for title, notes, time, and repeat intervals. Currently available for iOS only.
version: 0.0.6
homepage: https://github.com/aashutosh-dev1/in_app_reminder
repository: https://github.com/aashutosh-dev1/in_app_reminder
issue_tracker: https://github.com/aashutosh-dev1/in_app_reminder/issues

environment:
  sdk: ^3.7.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: InAppReminderPlugin
      # Android is not yet supported, but reserved for future
      # android:
      #   package: com.nextgenapps.inAppReminder.in_app_reminder
      #   pluginClass: InAppReminderPlugin
